spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.datasource.url=jdbc:h2:mem:test

#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
#spring.datasource.username=root
#spring.datasource.password=
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=pass@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

project.image=images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

spring.app.jwtSecret = mySecretKey123912738srestfvyjguidcyxdhgvjhgyufjyvh
spring.app.jwtExpirationMs =3000000
spring.ecom.app.jwtCookieName = springBootEcom

logging.level.org.springframework = DEBUG
logging.level.org.hibernate.sql = DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.com.ecommerce.project=DEBUG